### ISSUE TITLE
It dosent work

### ISSUE THREAD

**Issue by EndKingdom-Owner** [matthew4444/SimonSays-Need-More-Plugin-Files-Needs-Editing-#1]
Dont work

**Comment by matthew4444** [comment]
i said NEEDS EDITING

**Comment by EndKingdom-Owner** [comment]
**# Kk because i relly need it and can you add it on our group after you edited it and can you edit it soon after you done wirh the putting plugins**

**Comment by matthew4444** [comment]
Hey plz put http://www.mediafire.com/download/q79jchzs8h6gg16/Plugins.zip
EXTRACT IT TO THIS REPO

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
Srry wrong repo
